package com.juandiegogarcia.mapas.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a favorite place to be stored in the local Room database.
 * Each instance corresponds to a row in the "favorites" table.
 */
@Entity(tableName = "favorites")
data class FavoritePlace(
    /**
     * Unique ID for the place. It is autogenerated by Room.
     */
    @PrimaryKey(autoGenerate = true) val id: Int = 0,

    /**
     * Name given by the user to the location (e.g., "Home", "Park").
     */
    val name: String,

    /**
     * Geographic latitude of the location.
     */
    val latitude: Double,

    /**
     * Geographic longitude of the location.
     */
    val longitude: Double,

    /**
     * Indicates whether this place is marked as an alert point.
     */
    val isAlert: Boolean
)
